name: iOS CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - '*'

jobs:
  iOS:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=12.4,name=iPhone 12 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
    - uses: actions/checkout@v2
    - name: Git push
      run: |
        touch file
        git status
        git add .
        git commit -m "xcframework"
        git tag "0.63.4.4"
        git pull
        git push origin --tags
    - name: CocoaPods install
      run: | 
        pod --version
        cd example
        pod install --repo-update
    - name: Scheme Shared
      run: |
        cp -r Example/xcshareddata Example/Pods/Pods.xcodeproj
        rm -rf Example/Pods/Pods.xcodeproj/xcuserdata/*/*/react-ios.xcscheme
        rm -rf Example/Pods/Pods.xcodeproj/xcuserdata/*/*/glog.xcscheme
        rm -rf Example/Pods/Pods.xcodeproj/xcuserdata/*/*/DoubleConversion.xcscheme
        rm -rf Example/Pods/Pods.xcodeproj/xcuserdata/*/*/Yoga.xcscheme
    - name: Carthage build
      run: |
        carthage build --no-skip-current --use-xcframeworks
#     - name: Xcode build
#       run: | 
#         cd example
#         xcodebuild test -workspace ReactNativeCore.xcworkspace -scheme ReactNativeCore-Example
